$(document).ready(function()
{$('#btn_copy').click(function(e){window.location="copyFilter.htm?checklistID="+checklistID;return!1});if(typeof(checklistID)!=='undefined')
{$('#cl_name').editable('viewFilter.htm',{submitdata:{checklistID:checklistID},cancel:'Cancel',submit:'OK',indicator:'Saving...',tooltip:'Click to edit...',width:'60%'}).click(function(){$('#btn-cl-name').hide();$('.screen-head .h-bar').addClass('title-editing')})}
$('#btn-cl-name').click(function(){$('#cl_name').trigger('click');$(this).hide()});$("#cl_name").on("blur","input",function(e){$('.screen-head .h-bar').removeClass('title-editing');var showItems=function(){$('#btn-cl-name').show()};setTimeout(showItems,500)});$('#btn-add-spp').click(function(e)
{$('#filter-toolbar').hide();$('#add-toolbar').show();$('#add-spp-input').focus();var $searchClearBtn=$('#btn-search-clear');if($searchClearBtn.length>0){$searchClearBtn.hide()}
return!1});$('#btn-cancel-add-spp').click(function(e)
{$('#filter-toolbar').show();$('#add-toolbar').hide().removeClass('copy-new');$('#tbl_copynew_preview').hide();var $searchClearBtn=$('#btn-search-clear'),$inputSearch=$('#input-search');if($searchClearBtn.length>0&&$inputSearch.length>0){if($inputSearch.val().length>0){$searchClearBtn.show()}}
return!1});$('#btn_conf_cancel').click(function(e){$('#filter-toolbar').show();$('#add-toolbar').hide();enableInputs();$("#hid_add").removeAttr("name");$("#hid_add").removeAttr("value");$("#hid_add_from").removeAttr("name");$("#hid_add_from").removeAttr("value")});$('#btn_add_search').click(function(e){var searchStr=$("#add-spp-input").val();if(searchStr.length==0){return!1}
disableInputs();$("#hid_add").attr("name","addSpp");$("#hid_add").attr("value",searchStr);if(sppEditArr.length>0){launchNotSaved();return!1}
$("#fullChecklist").submit();return!1});$('#btn_rerun').click(function(e){$.ajax("/admin/rerun/checklist.do",{data:{r:checklistID},type:"POST",success:function(data)
{$('#btn_rerun').prop("disabled",!0);$('#rerun-confirm').modal('show')}});return!1});$('#view-desc').clickover({'content':function(){var content=$('#cl_desc_outer').html()+'<a href="#" id="btn-edit-desc" class="popover-foot">'+i18n.edit+'</a>';return content},'placement':'bottom','onShown':function(){$('#region-toggler').clickover('hide');if($('.cl-content').hasClass('editable')){$('.popover-content .cl-content').editable('viewFilter.htm',{submitdata:{checklistID:checklistID},cancel:'Cancel',submit:'Save',indicator:'Saving...',tooltip:'Click to edit...',type:'textarea',callback:function(value,settings){$('#cl_desc').html(value)},width:'245px',height:'150px'});$('#btn-edit-desc').click(function(){$('.popover-content .cl-content').trigger('click');$(this).hide()})}
$('.popover-content .cl-content').on('blur','textarea',function(e){var showItems=function(){$('#btn-edit-desc').show()};setTimeout(showItems,100)})}});if(regionCount>1){$('#region-label').html($('#region-label').html()+'s')}
if(regionCount>0)
$('#region-count').html(regionCount)})